[mypy]
python_version = 3.11
ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
strict_optional = True

[mypy-app.lib.*]
strict = True

[mypy-app]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True
