[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0f1117"
secondaryBackgroundColor = "#1e2130"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[runner]
fastRerenderEnabled = true
